.TH CAT 1
.SH NAME
cat \- concatenate files and write to standard output
.SH SYNOPSIS
.B cat file...
.fi
.SH DESCRIPTION
.I Cat
concatenates a set of files by opening them one at a time and writing
their contents to standard output.
Because standard output normally goes to the window in which the shell
runs, invoking \f2cat\f1 on a single file causes the contents of the file
to be written on the screen.
.SH SEE ALSO
cp(1), echo(1)
