.TH CP 1
.SH NAME
cp \- copies one or more files to a target
.SH SYNOPSIS
.B cp sourcefile destinationfile
.fi
.SH DESCRIPTION
.I Cp
copies file
.I sourcefile
to file
.I destinationfile.
.I Cp
uses the namespace when opening files, so it is possible
to copy a file to any device (e.g., the console).
.SH SEE ALSO
cat(1), mv(1), rm(1)
