.TH DATE 1
.SH NAME
date, time \- print the current time and date
.SH SYNOPSIS
.B date
.PP
.B time
.fi
.SH DESCRIPTION
.I Date
extracts the time from the operating system and formats it in a
readable form.
.PP
.I Time
is a synonym for the same function as
.I date.
.SH BUGS
\f2Date\f1 does not understand daylight savings time.
