.TH ECHO 1
.SH NAME
echo \- echo arguments to standard output device
.SH SYNOPSIS
.B echo argument...
.fi
.SH DESCRIPTION
.I Echo
prints its arguments separated by blanks on standard output.
It is useful for testing argument interpretation and for inserting
a constant string into a file.
.SH SEE ALSO
cat(1)
