.TH HELP 1
.SH NAME
help \- print a help message
.SH SYNOPSIS
.B help
.fi
.SH DESCRIPTION
.I Help
prints a help message that shows the possible commands available
under the shell.
Only command names are printed; the output is displayed with four
columns across the page to limit the length of the output.
.SH SEE ALSO
sh(1)
