.TH SCROLL 1
.SH NAME
scroll \- determine or set the screen scrolling rate
.SH SYNOPSIS
.B scroll [horizontal vertical]
.fi
.SH DESCRIPTION
With no arguments,
.I scroll
prints the current horizontal and vertical scrolling sensitivity
(the parameter that determines how fast the window scrolls for a given
offset from the center of the joystick icon).
With two arguments, \f2scroll\f1 sets the scrolling sensitivity to
the values given.
