.TH SLEEP 1
.SH NAME
sleep \- delay for a specified number of seconds
.SH SYNOPSIS
.B sleep delay
.fi
.SH DESCRIPTION
.I Sleep
delays for \f2delay\f1 seconds and then continues executing.
It is often useful in debugging because it gives a way to have
a process stay around with its standard input, output and error
files open.
.SH SEE ALSO
sleep(2)
