.TH UNMOUNT 1
.SH NAME
unmount \- remove an entry from the namespace prefix table
.SH SYNOPSIS
.B unmount prefix
.fi
.SH DESCRIPTION
.I Unmount
removes the entry from the namespace prefix mapping that has prefix
exactly equal to argument \f2prefix\f1.
.SH SEE ALSO
mount(1) mount(2) unmount(2) nam(4)
