.TH WHO 1
.SH NAME
who \- print name of user who is logged into the system
.SH SYNOPSIS
.B who
.SH DESCRIPTION
.I Who
prints the name of the user who is logged in and using the Xinu shell.
The printed information gives the user's name as well as the terminal
on which the shell executes.
.SH SEE ALSO
sh(1)
